project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "1_about/*.qmd"
    - "2_cv/*.qmd"
    - "3_posts/**/*.qmd"
    - "!bob.md"

website:
  title: "Peter T. Tanksley"
  search: false
  navbar: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

freeze: auto

