# render_cv_pubs.R — write 2_cv/_publications.qmd (the CV's publication block) from articles.yml.
#
# The CV includes the output with {{< include _publications.qmd >}}; nothing in it is edited by hand.
# Strings are printed verbatim from the YAML (authors_cv, title, venue, citation), so the generator
# never normalises anything Peter did not change himself.
#
# Run from the site repo root:  Rscript 5_skilltree/R/render_cv_pubs.R
# Override the output path (e.g. for a fidelity diff): PUBS_OUT=/tmp/x.qmd Rscript ...

suppressPackageStartupMessages({ library(here); library(yaml); library(purrr) })

arts <- read_yaml(here("5_skilltree", "data", "articles.yml"))
out  <- Sys.getenv("PUBS_OUT", unset = here("2_cv", "_publications.qmd"))

link_of <- function(a) if (!is.null(a$doi)) paste0("https://doi.org/", a$doi) else a$url

venue_part <- function(a) {
  link <- link_of(a)
  if (identical(a$status, "in_press") || is.null(link)) {
    tail <- if (identical(a$status, "in_press")) " (in press)." else if (!is.null(a$citation)) paste0(", ", a$citation, ".") else "."
    return(sprintf("*%s*%s", a$venue, tail))
  }
  tail <- if (is.null(a$citation)) "." else if (a$citation == "online first") " (online first)." else paste0(", ", a$citation, ".")
  sprintf("[*%s*](%s){target=\"_blank\"}%s", a$venue, link, tail)
}

articles  <- keep(arts, ~ .x$status != "preprint")
preprints <- keep(arts, ~ .x$status == "preprint")
stopifnot(all(map_lgl(articles, ~ !is.null(.x$cv_number))), !anyDuplicated(map_int(articles, "cv_number")))
articles  <- articles[order(-map_int(articles, "cv_number"))]

lines <- c("<!-- generated by 5_skilltree/R/render_cv_pubs.R from 5_skilltree/data/articles.yml; do not edit by hand -->",
           "", "### [Academic Articles]{.smallcaps}", "")
for (yr in sort(unique(map_int(articles, "year")), decreasing = TRUE)) {
  lines <- c(lines, sprintf("#### **%d**", yr), "")
  for (a in keep(articles, ~ .x$year == yr)) {
    lines <- c(lines, "::: {.pub-item}",
               sprintf("%d. %s<br>“%s.” %s", a$cv_number, a$authors_cv, a$title, venue_part(a)),
               ":::", "")
  }
}
if (length(preprints)) {
  lines <- c(lines, "### [Preprints]{.smallcaps}", "")
  for (a in preprints) {
    lines <- c(lines, "::: {.cv-indent}", paste0(a$authors_cv, "\\"),
               sprintf("\"%s.\" [*%s*](%s){target=\"_blank\"}.", a$title, a$venue, link_of(a)),
               ":::", "")
  }
}
writeLines(lines, out, useBytes = FALSE)
cat(sprintf("%s: %d articles (%d-%d), %d preprints\n", out, length(articles),
            min(map_int(articles, "year")), max(map_int(articles, "year")), length(preprints)))
